### ISSUE TITLE
Twitter: scrolling doesn't work

### ISSUE THREAD

**Issue by dstockhammer** [poberbichler/EHFG-App#48]
see title

**Comment by dstockhammer** [comment]
This is actually a bug that happens when the app gets upset with the amounts of actions you take in rapid succession.

Steps to repro:
tab around, hit back a few times, tab again, tap speakers, tab tab tab, tap tap, back back, bam

**Comment by poberbichler** [comment]
Nothing to do - was tested with old version, and is not going to be fixed any more
